version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
  - package-ecosystem: npm
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

