export const centerSection: string;
export const codeBlock: string;
export const docLink: string;
export const docsText: string;
export const headingSection: string;
export const inlineCodeBlock: string;
export const leftSection: string;
export const mainWrapper: string;
export const rightSection: string;
